---
- name: ensure dependencies available through apt are installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - nginx
    - php5
    - php5-fpm
    - roundcube
    - roundcube-mysql
    - roundcube-plugins
    - roundcube-plugins-extra

- name: ensure /srv/roundcube links to /var/lib/roundcube
  file:
    path: /srv/roundcube
    src: /var/lib/roundcube
    state: link

- name: ensure roundcube database is present
  mysql_db:
    name: roundcube
    state: present
  notify:
    - import roundcube database

- name: ensure roundcube database user is present
  mysql_user:
    name: roundcube
    host: "{{ item }}"
    password: "{{ roundcube_roundcube_mysql_password }}"
    priv: roundcube.*:ALL
  with_items:
    - "%"
    - localhost

- name: update /etc/nginx/sites-available/roundcube from template
  template:
    src: etc/nginx/sites-available/roundcube
    dest: /etc/nginx/sites-available/roundcube
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: ensure /etc/nginx/sites-enabled/roundcube exists and links to ../sites-available/roundcube
  file:
    path: /etc/nginx/sites-enabled/roundcube
    src: ../sites-available/roundcube
    force: yes
    state: link
  notify:
    - restart nginx

- name: ensure that there is not a hostname collision with the nginx default host
  lineinfile:
    dest: /etc/nginx/sites-available/default
    regexp: '^(\s+)(server_name {{ roundcube_hostname }};.*)$'
    backrefs: yes
    line: '\1#\2'
    state: present
  notify:
    - restart nginx

- name: ensure roundcube services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - nginx
    - php5-fpm

