---
- name: ensure roundcube packages and dependencies are installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - memcached
    - nginx
    - php5
    - php5-fpm
    - php5-memcached
    - roundcube
    - roundcube-mysql
    - roundcube-plugins
    - roundcube-plugins-extra

- name: ensure /srv/roundcube links to /var/lib/roundcube
  file:
    path: /srv/roundcube
    src: /var/lib/roundcube
    state: link

- name: ensure roundcube database is present
  mysql_db:
    name: roundcube
    state: present
  notify:
    - import roundcube database

- name: ensure roundcube database user is present
  mysql_user:
    name: roundcube
    host: "{{ item }}"
    password: "{{ roundcube_roundcube_mysql_password }}"
    priv: roundcube.*:ALL
  with_items:
    - "%"
    - localhost

- name: update /etc/dbconfig-common/roundcube.conf from template
  template:
    src: etc/dbconfig-common/roundcube.conf
    dest: /etc/dbconfig-common/roundcube.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - regenerate /etc/roundcube/debian-db.php

- name: update /etc/roundcube/main.inc.php from template
  template:
    src: etc/roundcube/main.inc.php
    dest: /etc/roundcube/main.inc.php
    owner: root
    group: www-data
    mode: 0640
  notify:
    - regenerate /etc/roundcube/debian-db.php

- name: update /etc/php5/fpm/pool.d/roundcube.conf from template
  template:
    src: etc/php5/fpm/pool.d/roundcube.conf
    dest: /etc/php5/fpm/pool.d/roundcube.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart php5-fpm

- name: update roundcube plugin configurations from templates
  template:
    src: usr/share/roundcube/plugins/{{ item }}/config.inc.php
    dest: /usr/share/roundcube/plugins/{{ item }}/config.inc.php
    owner: root
    group: www-data
    mode: 0640
  with_items:
    - markasjunk2
    - sieverules
    - zipdownload
  notify:
    - restart php5-fpm

- name: update /etc/nginx/sites-available/roundcube from template
  template:
    src: etc/nginx/sites-available/roundcube
    dest: /etc/nginx/sites-available/roundcube
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: ensure /etc/nginx/sites-enabled/roundcube exists and links to ../sites-available/roundcube
  file:
    path: /etc/nginx/sites-enabled/roundcube
    src: ../sites-available/roundcube
    force: yes
    state: link
  notify:
    - restart nginx

- name: ensure that there is not a hostname collision with the nginx default host
  lineinfile:
    dest: /etc/nginx/sites-available/default
    regexp: '^(\s+)(server_name {{ roundcube_hostname }};.*)$'
    backrefs: yes
    line: '\1#\2'
    state: present
  notify:
    - restart nginx

- name: ensure roundcube services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - nginx
    - php5-fpm

