---
- name: ensure dependencies available through apt are installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - nginx
    - php5
    - php5-fpm
    - roundcube
    - roundcube-mysql
    - roundcube-plugins
    - roundcube-plugins-extra

- name: ensure /srv/roundcube links to /var/lib/roundcube
  file:
    path: /srv/roundcube
    src: /var/lib/roundcube
    state: link

- name: ensure roundcube database is present
  mysql_db:
    name: roundcube
    target: /usr/share/dbconfig-common/data/roundcube/install/mysql
    state: import

- name: ensure roundcube database user is present
  mysql_user:
    name: roundcube
    host: "{{ item }}"
    password: "{{ roundcube_mysql_password }}"
    priv: roundcube.*:ALL
  with_items:
    - "%"
    - localhost

