---
- name: ensure dependencies available through apt are installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - nginx
    - php5
    - php5-fpm
    - roundcube
    - roundcube-mysql
    - roundcube-plugins
    - roundcube-plugins-extra
