---
- name: import roundcube database
  mysql_db:
    name: roundcube
    target: /usr/share/dbconfig-common/data/roundcube/install/mysql
    state: import

- name: restart php5-fpm
  service:
    name: php5-fpm
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted


