---
- name: import roundcube database
  mysql_db:
    name: roundcube
    target: /usr/share/dbconfig-common/data/roundcube/install/mysql
    state: import

- name: regenerate /etc/roundcube/debian-db.php
  command: dbconfig-generate-include -f php -O root:www-data -m 0640 /etc/dbconfig-common/roundcube.conf /etc/roundcube/debian-db.php

- name: restart php5-fpm
  service:
    name: php5-fpm
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted

